name: Personalize template README
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  personalize:
    if: github.repository != 'd3m1d0s/OpenGLTemplate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace repo links in README
        run: |
          REPO="${{ github.repository }}"   
          sed -i "s|d3m1d0s/OpenGLTemplate|$REPO|g" README.md
          sed -i "s|OWNER/REPO|$REPO|g" README.md
          sed -i "s|https://github.com/.*/.git|https://github.com/$REPO.git|g" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: personalize README with repository name"
